homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - page: home
    icon: fas fa-bolt
    children:
      - page: subpage-1
        next: subpage-2
      - page: subpage-2
        prev: subpage-1
